apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    build: wp-taurus-slave
  name: wp-taurus-slave
spec:
  output:
    to:
      kind: ImageStreamTag
      name: wp-taurus-slave:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/somebody/wp-taurus-slave
      ref: develop
    sourceSecret:
      name: builder-worldpay
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-slave-base-rhel7:latest
        namespace: openshift
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
